version: '3.1'
services:
 nameapp:
   container_name: "app-mongo"
   depends_on:
     - mongo
   restart: always
   build: .
   ports:
     - "3000:3000"
   networks:
     - app
   volumes:
     - .:/usr/app
 mongo:
   image: mongo
   container_name: mongodb
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: "juanayalaclabs"
     MONGO_INITDB_ROOT_PASSWORD: "LaLtmciVxpdpsaXy"
     MONGO_INITDB_DATABASE: "DEMO_ShoppingCart"
   ports:
     - 27017:27017
   networks:
     - app
   volumes:
     - ~/mongo/data:/data/db
networks:
 app:
   driver: "bridge"